/*CMD
  command: /adminPanel
  help: 
  need_reply: false
  auto_retry_time: 
  folder: Admin Panel

  <<ANSWER

  ANSWER

  <<KEYBOARD

  KEYBOARD
  aliases: 
  group: 
CMD*/

/* /adminPanel command – Admin view with real (resource) data and settings */

// भाषा-विशिष्ट डेटा ऑब्जेक्ट
var adminPanelLangData = {
  "EN": {
    welcome: "<b>👋 Hello {adminName}, welcome to the admin panel of {botLink}.</b>",
    latestDepositTitle: "<b>📥 Latest Deposit Notification:</b>",
    noRecentDeposits: "No recent deposits.",
    realStatisticsTitle: "<b>Real Statistics:</b>",
    totalMembers: "🧑 Total members: {status}",
    totalWithdrawn: "💸 Total withdrawn: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Total deposited: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Admin Settings:</b>",
    setCurrency: "💲 Set currency: {currency}",
    setBonus: "🎁 Set bonus: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Set per refer: {perRefer}%",
    setMinWithdraw: "💸 Set minimum withdraw: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Set maximum withdraw: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Set maintenance status: {maintenanceStatus}",
    setWithdrawal: "🏧 Set withdrawal status: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Set Auto Withdrawal Status: {autowithStatus}",
    setAlertsChannel: "🔴 Set alerts channel: {alertsChannel}",
    setMerchantAPI: "🗝️ Set merchant API key: {merchantAPI}",
    setPayoutAPI: "🗝️ Set payout API key: {payoutAPI}",
    btnAddBalance: "➕ Add balance",
    btnRemoveBalance: "➖ Remove balance",
    btnBanUser: "🚫 Ban user",
    btnUnbanUser: "✔️ Unban user",
    btnSetChannels: "🏘️ Set channel(s)",
    btnBroadcast: "📢 Broadcast",
    btnSetCurrency: "💲 Set currency: {currency}",
    btnSetBonus: "🎁 Set bonus: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Set per refer: {perRefer}%",
    btnSetMinWithdraw: "💸 Set minimum withdraw: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Set maximum withdraw: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Set maintenance status: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Set withdrawal status: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Set Auto Withdrawal Status: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Set alerts channel: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Set merchant API key: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Set payout API key: {payoutAPI}",
    btnViewUserBalance: "👀 View User Balance",
    notAdmin: "<i>⚠️ You're not the admin of {botLink}.</i>"
  },
  "IT": {
    welcome: "<b>👋 Ciao {adminName}, benvenuto nel pannello di amministrazione di {botLink}.</b>",
    latestDepositTitle: "<b>📥 Notifica ultimo deposito:</b>",
    noRecentDeposits: "Nessun deposito recente.",
    realStatisticsTitle: "<b>Statistiche Reali:</b>",
    totalMembers: "🧑 Totale membri: {status}",
    totalWithdrawn: "💸 Totale prelevato: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Totale depositato: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Impostazioni Admin:</b>",
    setCurrency: "💲 Imposta valuta: {currency}",
    setBonus: "🎁 Imposta bonus: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Imposta per referral: {perRefer}%",
    setMinWithdraw: "💸 Imposta prelievo minimo: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Imposta prelievo massimo: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Imposta stato manutenzione: {maintenanceStatus}",
    setWithdrawal: "🏧 Imposta stato prelievo: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Imposta stato prelievo automatico: {autowithStatus}",
    setAlertsChannel: "🔴 Imposta canale degli avvisi: {alertsChannel}",
    setMerchantAPI: "🗝️ Imposta chiave API merchant: {merchantAPI}",
    setPayoutAPI: "🗝️ Imposta chiave API payout: {payoutAPI}",
    btnAddBalance: "➕ Aggiungi saldo",
    btnRemoveBalance: "➖ Rimuovi saldo",
    btnBanUser: "🚫 Blocca utente",
    btnUnbanUser: "✔️ Sblocca utente",
    btnSetChannels: "🏘️ Imposta canale(i)",
    btnBroadcast: "📢 Trasmetti",
    btnSetCurrency: "💲 Imposta valuta: {currency}",
    btnSetBonus: "🎁 Imposta bonus: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Imposta per referral: {perRefer}%",
    btnSetMinWithdraw: "💸 Imposta prelievo minimo: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Imposta prelievo massimo: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Imposta stato manutenzione: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Imposta stato prelievo: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Imposta stato prelievo automatico: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Imposta canale avvisi: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Imposta chiave API merchant: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Imposta chiave API payout: {payoutAPI}",
    btnViewUserBalance: "👀 Visualizza saldo utente",
    notAdmin: "<i>⚠️ Non sei l'amministratore di {botLink}.</i>"
  },
  "ES": {
    welcome: "<b>👋 Hola {adminName}, bienvenido al panel de administración de {botLink}.</b>",
    latestDepositTitle: "<b>📥 Notificación de último depósito:</b>",
    noRecentDeposits: "No hay depósitos recientes.",
    realStatisticsTitle: "<b>Estadísticas Reales:</b>",
    totalMembers: "🧑 Total de miembros: {status}",
    totalWithdrawn: "💸 Total retirado: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Total depositado: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Configuración de Admin:</b>",
    setCurrency: "💲 Establecer moneda: {currency}",
    setBonus: "🎁 Establecer bono: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Establecer por referido: {perRefer}%",
    setMinWithdraw: "💸 Establecer retiro mínimo: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Establecer retiro máximo: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Establecer estado de mantenimiento: {maintenanceStatus}",
    setWithdrawal: "🏧 Establecer estado de retiro: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Establecer estado de retiro automático: {autowithStatus}",
    setAlertsChannel: "🔴 Establecer canal de alertas: {alertsChannel}",
    setMerchantAPI: "🗝️ Establecer clave API del comerciante: {merchantAPI}",
    setPayoutAPI: "🗝️ Establecer clave API de pago: {payoutAPI}",
    btnAddBalance: "➕ Añadir saldo",
    btnRemoveBalance: "➖ Quitar saldo",
    btnBanUser: "🚫 Bloquear usuario",
    btnUnbanUser: "✔️ Desbloquear usuario",
    btnSetChannels: "🏘️ Configurar canal(es)",
    btnBroadcast: "📢 Difundir",
    btnSetCurrency: "💲 Establecer moneda: {currency}",
    btnSetBonus: "🎁 Establecer bono: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Establecer por referido: {perRefer}%",
    btnSetMinWithdraw: "💸 Establecer retiro mínimo: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Establecer retiro máximo: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Establecer estado de mantenimiento: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Establecer estado de retiro: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Establecer estado de retiro automático: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Establecer canal de alertas: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Establecer clave API del comerciante: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Establecer clave API de pago: {payoutAPI}",
    btnViewUserBalance: "👀 Ver saldo del usuario",
    notAdmin: "<i>⚠️ No eres el administrador de {botLink}.</i>"
  },
  "PT": {
    welcome: "<b>👋 Olá {adminName}, bem-vindo ao painel de administração de {botLink}.</b>",
    latestDepositTitle: "<b>📥 Notificação do último depósito:</b>",
    noRecentDeposits: "Nenhum depósito recente.",
    realStatisticsTitle: "<b>Estatísticas Reais:</b>",
    totalMembers: "🧑 Total de membros: {status}",
    totalWithdrawn: "💸 Total retirado: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Total depositado: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Configurações do Admin:</b>",
    setCurrency: "💲 Definir moeda: {currency}",
    setBonus: "🎁 Definir bônus: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Definir por indicação: {perRefer}%",
    setMinWithdraw: "💸 Definir saque mínimo: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Definir saque máximo: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Definir status de manutenção: {maintenanceStatus}",
    setWithdrawal: "🏧 Definir status de saque: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Definir status de saque automático: {autowithStatus}",
    setAlertsChannel: "🔴 Definir canal de alertas: {alertsChannel}",
    setMerchantAPI: "🗝️ Definir chave API do comerciante: {merchantAPI}",
    setPayoutAPI: "🗝️ Definir chave API de pagamento: {payoutAPI}",
    btnAddBalance: "➕ Adicionar saldo",
    btnRemoveBalance: "➖ Remover saldo",
    btnBanUser: "🚫 Banir usuário",
    btnUnbanUser: "✔️ Desbanir usuário",
    btnSetChannels: "🏘️ Definir canal(is)",
    btnBroadcast: "📢 Transmitir",
    btnSetCurrency: "💲 Definir moeda: {currency}",
    btnSetBonus: "🎁 Definir bônus: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Definir por indicação: {perRefer}%",
    btnSetMinWithdraw: "💸 Definir saque mínimo: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Definir saque máximo: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Definir status de manutenção: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Definir status de saque: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Definir status de saque automático: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Definir canal de alertas: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Definir chave API do comerciante: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Definir chave API de pagamento: {payoutAPI}",
    btnViewUserBalance: "👀 Visualizar saldo do usuário",
    notAdmin: "<i>⚠️ Você não é o administrador de {botLink}.</i>"
  },
  "DE": {
    welcome: "<b>👋 Hallo {adminName}, willkommen im Admin-Bereich von {botLink}.</b>",
    latestDepositTitle: "<b>📥 Neueste Einzahlungsmeldung:</b>",
    noRecentDeposits: "Keine aktuellen Einzahlungen.",
    realStatisticsTitle: "<b>Echte Statistiken:</b>",
    totalMembers: "🧑 Gesamtmitglieder: {status}",
    totalWithdrawn: "💸 Insgesamt abgehoben: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Insgesamt eingezahlt: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Admin-Einstellungen:</b>",
    setCurrency: "💲 Währung festlegen: {currency}",
    setBonus: "🎁 Bonus festlegen: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Pro Empfehlung festlegen: {perRefer}%",
    setMinWithdraw: "💸 Mindestabhebung festlegen: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Höchstabhebung festlegen: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Wartungsstatus festlegen: {maintenanceStatus}",
    setWithdrawal: "🏧 Abhebestatus festlegen: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Automatischen Abhebestatus festlegen: {autowithStatus}",
    setAlertsChannel: "🔴 Alarmkanal festlegen: {alertsChannel}",
    setMerchantAPI: "🗝️ Händler-API-Schlüssel festlegen: {merchantAPI}",
    setPayoutAPI: "🗝️ Auszahlungs-API-Schlüssel festlegen: {payoutAPI}",
    btnAddBalance: "➕ Guthaben hinzufügen",
    btnRemoveBalance: "➖ Guthaben entfernen",
    btnBanUser: "🚫 Benutzer sperren",
    btnUnbanUser: "✔️ Benutzer entsperren",
    btnSetChannels: "🏘️ Kanal(e) festlegen",
    btnBroadcast: "📢 Senden",
    btnSetCurrency: "💲 Währung festlegen: {currency}",
    btnSetBonus: "🎁 Bonus festlegen: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Pro Empfehlung festlegen: {perRefer}%",
    btnSetMinWithdraw: "💸 Mindestabhebung festlegen: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Höchstabhebung festlegen: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Wartungsstatus festlegen: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Abhebestatus festlegen: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Automatischen Abhebestatus festlegen: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Alarmkanal festlegen: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Händler-API-Schlüssel festlegen: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Auszahlungs-API-Schlüssel festlegen: {payoutAPI}",
    btnViewUserBalance: "👀 Benutzerguthaben anzeigen",
    notAdmin: "<i>⚠️ Du bist nicht der Administrator von {botLink}.</i>"
  },
  "FR": {
    welcome: "<b>👋 Bonjour {adminName}, bienvenue dans le panneau d'administration de {botLink}.</b>",
    latestDepositTitle: "<b>📥 Dernière notification de dépôt :</b>",
    noRecentDeposits: "Aucun dépôt récent.",
    realStatisticsTitle: "<b>Statistiques Réelles :</b>",
    totalMembers: "🧑 Nombre total de membres : {status}",
    totalWithdrawn: "💸 Total retiré : {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Total déposé : {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Paramètres Admin :</b>",
    setCurrency: "💲 Définir la devise : {currency}",
    setBonus: "🎁 Définir le bonus : {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Définir par parrainage : {perRefer}%",
    setMinWithdraw: "💸 Définir le retrait minimum : {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Définir le retrait maximum : {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Définir le statut de maintenance : {maintenanceStatus}",
    setWithdrawal: "🏧 Définir le statut de retrait : {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Définir le statut de retrait automatique : {autowithStatus}",
    setAlertsChannel: "🔴 Définir le canal d'alertes : {alertsChannel}",
    setMerchantAPI: "🗝️ Définir la clé API marchand : {merchantAPI}",
    setPayoutAPI: "🗝️ Définir la clé API de paiement : {payoutAPI}",
    btnAddBalance: "➕ Ajouter du solde",
    btnRemoveBalance: "➖ Retirer du solde",
    btnBanUser: "🚫 Bloquer l'utilisateur",
    btnUnbanUser: "✔️ Débloquer l'utilisateur",
    btnSetChannels: "🏘️ Définir le(s) canal(aux)",
    btnBroadcast: "📢 Diffuser",
    btnSetCurrency: "💲 Définir la devise : {currency}",
    btnSetBonus: "🎁 Définir le bonus : {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Définir par parrainage : {perRefer}%",
    btnSetMinWithdraw: "💸 Définir le retrait minimum : {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Définir le retrait maximum : {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Définir le statut de maintenance : {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Définir le statut de retrait : {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Définir le statut de retrait automatique : {autowithStatus}",
    btnSetAlertsChannel: "🔴 Définir le canal d'alertes : {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Définir la clé API marchand : {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Définir la clé API de paiement : {payoutAPI}",
    btnViewUserBalance: "👀 Voir le solde de l'utilisateur",
    notAdmin: "<i>⚠️ Vous n'êtes pas l'administrateur de {botLink}.</i>"
  },
  "RU": {
    welcome: "<b>👋 Привет, {adminName}, добро пожаловать в админ-панель {botLink}.</b>",
    latestDepositTitle: "<b>📥 Последнее уведомление о депозите:</b>",
    noRecentDeposits: "Недавних депозитов нет.",
    realStatisticsTitle: "<b>Реальная статистика:</b>",
    totalMembers: "🧑 Всего участников: {status}",
    totalWithdrawn: "💸 Всего выведено: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Всего внесено: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Настройки администратора:</b>",
    setCurrency: "💲 Установить валюту: {currency}",
    setBonus: "🎁 Установить бонус: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Установить за реферала: {perRefer}%",
    setMinWithdraw: "💸 Установить минимальный вывод: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Установить максимальный вывод: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Установить статус обслуживания: {maintenanceStatus}",
    setWithdrawal: "🏧 Установить статус вывода: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Установить статус автоматического вывода: {autowithStatus}",
    setAlertsChannel: "🔴 Установить канал оповещений: {alertsChannel}",
    setMerchantAPI: "🗝️ Установить API-ключ продавца: {merchantAPI}",
    setPayoutAPI: "🗝️ Установить API-ключ выплат: {payoutAPI}",
    btnAddBalance: "➕ Добавить баланс",
    btnRemoveBalance: "➖ Удалить баланс",
    btnBanUser: "🚫 Заблокировать пользователя",
    btnUnbanUser: "✔️ Разблокировать пользователя",
    btnSetChannels: "🏘️ Установить канал(ы)",
    btnBroadcast: "📢 Рассылка",
    btnSetCurrency: "💲 Установить валюту: {currency}",
    btnSetBonus: "🎁 Установить бонус: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Установить за реферала: {perRefer}%",
    btnSetMinWithdraw: "💸 Установить минимальный вывод: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Установить максимальный вывод: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Установить статус обслуживания: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Установить статус вывода: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Установить статус автоматического вывода: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Установить канал оповещений: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Установить API-ключ продавца: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Установить API-ключ выплат: {payoutAPI}",
    btnViewUserBalance: "👀 Посмотреть баланс пользователя",
    notAdmin: "<i>⚠️ Вы не администратор {botLink}.</i>"
  },
  "ZH": {
    welcome: "<b>👋 你好 {adminName}, 欢迎来到 {botLink} 的管理员面板。</b>",
    latestDepositTitle: "<b>📥 最新存款通知：</b>",
    noRecentDeposits: "没有最近的存款。",
    realStatisticsTitle: "<b>实际统计数据：</b>",
    totalMembers: "🧑 总成员数：{status}",
    totalWithdrawn: "💸 总提现：{totalWithdrawn} {currency}",
    totalDeposited: "🔥 总存款：{totalDeposits} {currency}",
    adminSettingsTitle: "<b>管理员设置：</b>",
    setCurrency: "💲 设置货币：{currency}",
    setBonus: "🎁 设置奖金：{bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 设置每推荐：{perRefer}%",
    setMinWithdraw: "💸 设置最低提现：{minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 设置最高提现：{maximumWithdraw} {currency}",
    setMaintenance: "🛠️ 设置维护状态：{maintenanceStatus}",
    setWithdrawal: "🏧 设置提现状态：{withdrawalStatus}",
    setAutoWithdrawal: "🏧 设置自动提现状态：{autowithStatus}",
    setAlertsChannel: "🔴 设置提醒频道：{alertsChannel}",
    setMerchantAPI: "🗝️ 设置商户 API 密钥：{merchantAPI}",
    setPayoutAPI: "🗝️ 设置支付 API 密钥：{payoutAPI}",
    btnAddBalance: "➕ 添加余额",
    btnRemoveBalance: "➖ 移除余额",
    btnBanUser: "🚫 封禁用户",
    btnUnbanUser: "✔️ 解除封禁",
    btnSetChannels: "🏘️ 设置频道",
    btnBroadcast: "📢 广播",
    btnSetCurrency: "💲 设置货币：{currency}",
    btnSetBonus: "🎁 设置奖金：{bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 设置每推荐：{perRefer}%",
    btnSetMinWithdraw: "💸 设置最低提现：{minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 设置最高提现：{maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ 设置维护状态：{maintenanceStatus}",
    btnSetWithdrawal: "🏧 设置提现状态：{withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 设置自动提现状态：{autowithStatus}",
    btnSetAlertsChannel: "🔴 设置提醒频道：{alertsChannel}",
    btnSetMerchantAPI: "🗝️ 设置商户 API 密钥：{merchantAPI}",
    btnSetPayoutAPI: "🗝️ 设置支付 API 密钥：{payoutAPI}",
    btnViewUserBalance: "👀 查看用户余额",
    notAdmin: "<i>⚠️ 你不是 {botLink} 的管理员。</i>"
  },
  "HI": {
    welcome: "<b>👋 नमस्ते {adminName}, {botLink} के एडमिन पैनल में आपका स्वागत है।</b>",
    latestDepositTitle: "<b>📥 नवीनतम जमा अधिसूचना:</b>",
    noRecentDeposits: "कोई हाल ही में जमा नहीं हुए।",
    realStatisticsTitle: "<b>वास्तविक आँकड़े:</b>",
    totalMembers: "🧑 कुल सदस्य: {status}",
    totalWithdrawn: "💸 कुल निकासी: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 कुल जमा: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>एडमिन सेटिंग्स:</b>",
    setCurrency: "💲 मुद्रा सेट करें: {currency}",
    setBonus: "🎁 बोनस सेट करें: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 प्रति रेफ़रल सेट करें: {perRefer}%",
    setMinWithdraw: "💸 न्यूनतम निकासी सेट करें: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 अधिकतम निकासी सेट करें: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ मेंटेनेंस स्टेटस सेट करें: {maintenanceStatus}",
    setWithdrawal: "🏧 निकासी स्टेटस सेट करें: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 ऑटो निकासी स्टेटस सेट करें: {autowithStatus}",
    setAlertsChannel: "🔴 अलर्ट्स चैनल सेट करें: {alertsChannel}",
    setMerchantAPI: "🗝️ मर्चेंट API की सेट करें: {merchantAPI}",
    setPayoutAPI: "🗝️ पेडआउट API की सेट करें: {payoutAPI}",
    btnAddBalance: "➕ बैलेंस जोड़ें",
    btnRemoveBalance: "➖ बैलेंस हटाएं",
    btnBanUser: "🚫 उपयोगकर्ता को प्रतिबंधित करें",
    btnUnbanUser: "✔️ उपयोगकर्ता का प्रतिबंध हटाएं",
    btnSetChannels: "🏘️ चैनल सेट करें",
    btnBroadcast: "📢 ब्रॉडकास्ट करें",
    btnSetCurrency: "💲 मुद्रा सेट करें: {currency}",
    btnSetBonus: "🎁 बोनस सेट करें: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 प्रति रेफ़रल सेट करें: {perRefer}%",
    btnSetMinWithdraw: "💸 न्यूनतम निकासी सेट करें: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 अधिकतम निकासी सेट करें: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ मेंटेनेंस स्टेटस सेट करें: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 निकासी स्टेटस सेट करें: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 ऑटो निकासी स्टेटस सेट करें: {autowithStatus}",
    btnSetAlertsChannel: "🔴 अलर्ट्स चैनल सेट करें: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ मर्चेंट API की सेट करें: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ पेडआउट API की सेट करें: {payoutAPI}",
    btnViewUserBalance: "👀 उपयोगकर्ता बैलेंस देखें",
    notAdmin: "<i>⚠️ आप {botLink} के एडमिन नहीं हैं।</i>"
  },
  "UR": {
    welcome: "<b>👋 سلام {adminName}, {botLink} کے ایڈمن پینل میں خوش آمدید۔</b>",
    latestDepositTitle: "<b>📥 تازہ ترین جمع کی اطلاع:</b>",
    noRecentDeposits: "حال ہی میں کوئی جمع نہیں ہوئی۔",
    realStatisticsTitle: "<b>اصلی شماریات:</b>",
    totalMembers: "🧑 کل ممبران: {status}",
    totalWithdrawn: "💸 کل نکالا گیا: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 کل جمع کیا گیا: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>ایڈمن سیٹنگز:</b>",
    setCurrency: "💲 کرنسی سیٹ کریں: {currency}",
    setBonus: "🎁 بونس سیٹ کریں: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 فی ریفر سیٹ کریں: {perRefer}%",
    setMinWithdraw: "💸 کم از کم نکاسی سیٹ کریں: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 زیادہ سے زیادہ نکاسی سیٹ کریں: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ مینٹیننس اسٹیٹس سیٹ کریں: {maintenanceStatus}",
    setWithdrawal: "🏧 نکاسی اسٹیٹس سیٹ کریں: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 آٹو نکاسی اسٹیٹس سیٹ کریں: {autowithStatus}",
    setAlertsChannel: "🔴 الرٹس چینل سیٹ کریں: {alertsChannel}",
    setMerchantAPI: "🗝️ مرچنٹ API کی سیٹ کریں: {merchantAPI}",
    setPayoutAPI: "🗝️ پے آؤٹ API کی سیٹ کریں: {payoutAPI}",
    btnAddBalance: "➕ بیلنس شامل کریں",
    btnRemoveBalance: "➖ بیلنس نکالیں",
    btnBanUser: "🚫 یوزر کو بین کریں",
    btnUnbanUser: "✔️ یوزر کا بین ہٹا دیں",
    btnSetChannels: "🏘️ چینلز سیٹ کریں",
    btnBroadcast: "📢 براڈکاسٹ کریں",
    btnSetCurrency: "💲 کرنسی سیٹ کریں: {currency}",
    btnSetBonus: "🎁 بونس سیٹ کریں: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 فی ریفر سیٹ کریں: {perRefer}%",
    btnSetMinWithdraw: "💸 کم از کم نکاسی سیٹ کریں: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 زیادہ سے زیادہ نکاسی سیٹ کریں: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ مینٹیننس اسٹیٹس سیٹ کریں: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 نکاسی اسٹیٹس سیٹ کریں: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 آٹو نکاسی اسٹیٹس سیٹ کریں: {autowithStatus}",
    btnSetAlertsChannel: "🔴 الرٹس چینل سیٹ کریں: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ مرچنٹ API کی سیٹ کریں: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ پے آؤٹ API کی سیٹ کریں: {payoutAPI}",
    btnViewUserBalance: "👀 یوزر بیلنس دیکھیں",
    notAdmin: "<i>⚠️ آپ {botLink} کے ایڈمن نہیں ہیں۔</i>"
  },
  "BN": {
    welcome: "<b>👋 হ্যালো {adminName}, {botLink} এর অ্যাডমিন প্যানেলে স্বাগতম।</b>",
    latestDepositTitle: "<b>📥 সর্বশেষ ডিপোজিট বিজ্ঞপ্তি:</b>",
    noRecentDeposits: "সাম্প্রতিক কোনো ডিপোজিট নেই।",
    realStatisticsTitle: "<b>বাস্তব পরিসংখ্যান:</b>",
    totalMembers: "🧑 মোট সদস্য: {status}",
    totalWithdrawn: "💸 মোট উত্তোলন: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 মোট জমা: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>অ্যাডমিন সেটিংস:</b>",
    setCurrency: "💲 মুদ্রা সেট করুন: {currency}",
    setBonus: "🎁 বোনাস সেট করুন: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 প্রতি রেফার সেট করুন: {perRefer}%",
    setMinWithdraw: "💸 সর্বনিম্ন উত্তোলন সেট করুন: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 সর্বোচ্চ উত্তোলন সেট করুন: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ মেইনটেনেন্স স্ট্যাটাস সেট করুন: {maintenanceStatus}",
    setWithdrawal: "🏧 উত্তোলন স্ট্যাটাস সেট করুন: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 অটো উত্তোলন স্ট্যাটাস সেট করুন: {autowithStatus}",
    setAlertsChannel: "🔴 অ্যালার্টস চ্যানেল সেট করুন: {alertsChannel}",
    setMerchantAPI: "🗝️ মার্চেন্ট API কী সেট করুন: {merchantAPI}",
    setPayoutAPI: "🗝️ পে আউট API কী সেট করুন: {payoutAPI}",
    btnAddBalance: "➕ ব্যালেন্স যোগ করুন",
    btnRemoveBalance: "➖ ব্যালেন্স কমান",
    btnBanUser: "🚫 ইউজারকে ব্যান করুন",
    btnUnbanUser: "✔️ ইউজারের ব্যান খুলুন",
    btnSetChannels: "🏘️ চ্যানেল সেট করুন",
    btnBroadcast: "📢 সম্প্রচার করুন",
    btnSetCurrency: "💲 মুদ্রা সেট করুন: {currency}",
    btnSetBonus: "🎁 বোনাস সেট করুন: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 প্রতি রেফার সেট করুন: {perRefer}%",
    btnSetMinWithdraw: "💸 সর্বনিম্ন উত্তোলন সেট করুন: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 সর্বোচ্চ উত্তোলন সেট করুন: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ মেইনটেনেন্স স্ট্যাটাস সেট করুন: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 উত্তোলন স্ট্যাটাস সেট করুন: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 অটো উত্তোলন স্ট্যাটাস সেট করুন: {autowithStatus}",
    btnSetAlertsChannel: "🔴 অ্যালার্টস চ্যানেল সেট করুন: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ মার্চেন্ট API কী সেট করুন: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ পে আউট API কী সেট করুন: {payoutAPI}",
    btnViewUserBalance: "👀 ইউজার ব্যালেন্স দেখুন",
    notAdmin: "<i>⚠️ আপনি {botLink} এর অ্যাডমিন নন।</i>"
  },
  "AR": {
    welcome: "<b>👋 مرحبًا {adminName}، أهلاً بك في لوحة تحكم الإدارة لـ {botLink}.</b>",
    latestDepositTitle: "<b>📥 أحدث إشعار بالإيداع:</b>",
    noRecentDeposits: "لا توجد إيداعات حديثة.",
    realStatisticsTitle: "<b>الإحصائيات الحقيقية:</b>",
    totalMembers: "🧑 إجمالي الأعضاء: {status}",
    totalWithdrawn: "💸 إجمالي المسحوبات: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 إجمالي الإيداعات: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>إعدادات الإدارة:</b>",
    setCurrency: "💲 تعيين العملة: {currency}",
    setBonus: "🎁 تعيين البونص: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 تعيين لكل إحالة: {perRefer}%",
    setMinWithdraw: "💸 تعيين الحد الأدنى للسحب: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 تعيين الحد الأقصى للسحب: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ تعيين حالة الصيانة: {maintenanceStatus}",
    setWithdrawal: "🏧 تعيين حالة السحب: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 تعيين حالة السحب التلقائي: {autowithStatus}",
    setAlertsChannel: "🔴 تعيين قناة التنبيهات: {alertsChannel}",
    setMerchantAPI: "🗝️ تعيين مفتاح API للتاجر: {merchantAPI}",
    setPayoutAPI: "🗝️ تعيين مفتاح API للدفع: {payoutAPI}",
    btnAddBalance: "➕ إضافة رصيد",
    btnRemoveBalance: "➖ إزالة رصيد",
    btnBanUser: "🚫 حظر المستخدم",
    btnUnbanUser: "✔️ إلغاء حظر المستخدم",
    btnSetChannels: "🏘️ تعيين القناة(القنوات)",
    btnBroadcast: "📢 البث",
    btnSetCurrency: "💲 تعيين العملة: {currency}",
    btnSetBonus: "🎁 تعيين البونص: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 تعيين لكل إحالة: {perRefer}%",
    btnSetMinWithdraw: "💸 تعيين الحد الأدنى للسحب: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 تعيين الحد الأقصى للسحب: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ تعيين حالة الصيانة: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 تعيين حالة السحب: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 تعيين حالة السحب التلقائي: {autowithStatus}",
    btnSetAlertsChannel: "🔴 تعيين قناة التنبيهات: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ تعيين مفتاح API للتاجر: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ تعيين مفتاح API للدفع: {payoutAPI}",
    btnViewUserBalance: "👀 عرض رصيد المستخدم",
    notAdmin: "<i>⚠️ أنت لست المسؤول عن {botLink}.</i>"
  },
  "TR": {
    welcome: "<b>👋 Merhaba {adminName}, {botLink} yönetici paneline hoş geldiniz.</b>",
    latestDepositTitle: "<b>📥 Son Depozit Bildirimi:</b>",
    noRecentDeposits: "Yakın zamanda depozit yapılmamış.",
    realStatisticsTitle: "<b>Gerçek İstatistikler:</b>",
    totalMembers: "🧑 Toplam üyeler: {status}",
    totalWithdrawn: "💸 Toplam çekilen: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Toplam yatırılan: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Yönetici Ayarları:</b>",
    setCurrency: "💲 Para birimini ayarla: {currency}",
    setBonus: "🎁 Bonus ayarla: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 Her referans için ayarla: {perRefer}%",
    setMinWithdraw: "💸 Minimum çekim ayarla: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 Maksimum çekim ayarla: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ Bakım durumunu ayarla: {maintenanceStatus}",
    setWithdrawal: "🏧 Çekim durumunu ayarla: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 Otomatik çekim durumunu ayarla: {autowithStatus}",
    setAlertsChannel: "🔴 Uyarı kanalını ayarla: {alertsChannel}",
    setMerchantAPI: "🗝️ Satıcı API anahtarını ayarla: {merchantAPI}",
    setPayoutAPI: "🗝️ Ödeme API anahtarını ayarla: {payoutAPI}",
    btnAddBalance: "➕ Bakiye ekle",
    btnRemoveBalance: "➖ Bakiye çıkar",
    btnBanUser: "🚫 Kullanıcıyı yasakla",
    btnUnbanUser: "✔️ Kullanıcının yasağını kaldır",
    btnSetChannels: "🏘️ Kanal(ları) ayarla",
    btnBroadcast: "📢 Yayınla",
    btnSetCurrency: "💲 Para birimini ayarla: {currency}",
    btnSetBonus: "🎁 Bonus ayarla: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 Her referans için ayarla: {perRefer}%",
    btnSetMinWithdraw: "💸 Minimum çekim ayarla: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 Maksimum çekim ayarla: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ Bakım durumunu ayarla: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 Çekim durumunu ayarla: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 Otomatik çekim durumunu ayarla: {autowithStatus}",
    btnSetAlertsChannel: "🔴 Uyarı kanalını ayarla: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ Satıcı API anahtarını ayarla: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ Ödeme API anahtarını ayarla: {payoutAPI}",
    btnViewUserBalance: "👀 Kullanıcı bakiyesini görüntüle",
    notAdmin: "<i>⚠️ {botLink} yönetici değilsiniz.</i>"
  },
  "KO": {
    welcome: "<b>👋 안녕하세요 {adminName}, {botLink} 관리자 패널에 오신 것을 환영합니다.</b>",
    latestDepositTitle: "<b>📥 최신 입금 알림:</b>",
    noRecentDeposits: "최근 입금 내역이 없습니다.",
    realStatisticsTitle: "<b>실제 통계:</b>",
    totalMembers: "🧑 총 회원 수: {status}",
    totalWithdrawn: "💸 총 출금액: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 총 입금액: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>관리자 설정:</b>",
    setCurrency: "💲 통화 설정: {currency}",
    setBonus: "🎁 보너스 설정: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 추천 당 설정: {perRefer}%",
    setMinWithdraw: "💸 최소 출금액 설정: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 최대 출금액 설정: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ 유지보수 상태 설정: {maintenanceStatus}",
    setWithdrawal: "🏧 출금 상태 설정: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 자동 출금 상태 설정: {autowithStatus}",
    setAlertsChannel: "🔴 알림 채널 설정: {alertsChannel}",
    setMerchantAPI: "🗝️ 상인 API 키 설정: {merchantAPI}",
    setPayoutAPI: "🗝️ 지급 API 키 설정: {payoutAPI}",
    btnAddBalance: "➕ 잔액 추가",
    btnRemoveBalance: "➖ 잔액 제거",
    btnBanUser: "🚫 사용자 차단",
    btnUnbanUser: "✔️ 사용자 차단 해제",
    btnSetChannels: "🏘️ 채널 설정",
    btnBroadcast: "📢 방송",
    btnSetCurrency: "💲 통화 설정: {currency}",
    btnSetBonus: "🎁 보너스 설정: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 추천 당 설정: {perRefer}%",
    btnSetMinWithdraw: "💸 최소 출금액 설정: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 최대 출금액 설정: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ 유지보수 상태 설정: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 출금 상태 설정: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 자동 출금 상태 설정: {autowithStatus}",
    btnSetAlertsChannel: "🔴 알림 채널 설정: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ 상인 API 키 설정: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ 지급 API 키 설정: {payoutAPI}",
    btnViewUserBalance: "👀 사용자 잔액 보기",
    notAdmin: "<i>⚠️ 당신은 {botLink}의 관리자가 아닙니다.</i>"
  },
  "FIL": {
    welcome: "<b>👋 Kamusta {adminName}, maligayang pagdating sa admin panel ng {botLink}.</b>",
    latestDepositTitle: "<b>📥 Pinakabagong Deposit Notification:</b>",
    noRecentDeposits: "Walang kamakailang deposito.",
    realStatisticsTitle: "<b>Tunay na Estadistika:</b>",
    totalMembers: "🧑 Kabuuang miyembro: {status}",
    totalWithdrawn: "💸 Kabuuang nakuha: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 Kabuuang na-deposito: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>Admin Settings:</b>",
    setCurrency: "💲 I-set ang currency: {currency}",
    setBonus: "🎁 I-set ang bonus: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 I-set ang per refer: {perRefer}%",
    setMinWithdraw: "💸 I-set ang minimum withdraw: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 I-set ang maximum withdraw: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ I-set ang maintenance status: {maintenanceStatus}",
    setWithdrawal: "🏧 I-set ang withdrawal status: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 I-set ang auto withdrawal status: {autowithStatus}",
    setAlertsChannel: "🔴 I-set ang alerts channel: {alertsChannel}",
    setMerchantAPI: "🗝️ I-set ang merchant API key: {merchantAPI}",
    setPayoutAPI: "🗝️ I-set ang payout API key: {payoutAPI}",
    btnAddBalance: "➕ Magdagdag ng balance",
    btnRemoveBalance: "➖ Alisin ang balance",
    btnBanUser: "🚫 I-ban ang user",
    btnUnbanUser: "✔️ I-unban ang user",
    btnSetChannels: "🏘️ I-set ang channel(s)",
    btnBroadcast: "📢 I-broadcast",
    btnSetCurrency: "💲 I-set ang currency: {currency}",
    btnSetBonus: "🎁 I-set ang bonus: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 I-set ang per refer: {perRefer}%",
    btnSetMinWithdraw: "💸 I-set ang minimum withdraw: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 I-set ang maximum withdraw: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ I-set ang maintenance status: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 I-set ang withdrawal status: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 I-set ang auto withdrawal status: {autowithStatus}",
    btnSetAlertsChannel: "🔴 I-set ang alerts channel: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ I-set ang merchant API key: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ I-set ang payout API key: {payoutAPI}",
    btnViewUserBalance: "👀 Tingnan ang balance ng user",
    notAdmin: "<i>⚠️ Hindi ka admin ng {botLink}.</i>"
  },
  "JA": {
    welcome: "<b>👋 こんにちは {adminName}、{botLink} の管理パネルへようこそ。</b>",
    latestDepositTitle: "<b>📥 最新の入金通知：</b>",
    noRecentDeposits: "最近の入金はありません。",
    realStatisticsTitle: "<b>実際の統計:</b>",
    totalMembers: "🧑 総メンバー数: {status}",
    totalWithdrawn: "💸 総出金額: {totalWithdrawn} {currency}",
    totalDeposited: "🔥 総入金額: {totalDeposits} {currency}",
    adminSettingsTitle: "<b>管理者設定:</b>",
    setCurrency: "💲 通貨を設定: {currency}",
    setBonus: "🎁 ボーナスを設定: {bonus} {currency}",
    setPerRefer: "🧑‍🤝‍🧑 紹介ごとに設定: {perRefer}%",
    setMinWithdraw: "💸 最低出金額を設定: {minimumWithdraw} {currency}",
    setMaxWithdraw: "💸 最高出金額を設定: {maximumWithdraw} {currency}",
    setMaintenance: "🛠️ メンテナンス状態を設定: {maintenanceStatus}",
    setWithdrawal: "🏧 出金状態を設定: {withdrawalStatus}",
    setAutoWithdrawal: "🏧 自動出金状態を設定: {autowithStatus}",
    setAlertsChannel: "🔴 アラートチャンネルを設定: {alertsChannel}",
    setMerchantAPI: "🗝️ マーチャントAPIキーを設定: {merchantAPI}",
    setPayoutAPI: "🗝️ ペイアウトAPIキーを設定: {payoutAPI}",
    btnAddBalance: "➕ 残高を追加",
    btnRemoveBalance: "➖ 残高を削除",
    btnBanUser: "🚫 ユーザーを禁止",
    btnUnbanUser: "✔️ ユーザーの禁止を解除",
    btnSetChannels: "🏘️ チャンネルを設定",
    btnBroadcast: "📢 ブロードキャスト",
    btnSetCurrency: "💲 通貨を設定: {currency}",
    btnSetBonus: "🎁 ボーナスを設定: {bonus} {currency}",
    btnSetPerRefer: "🧑‍🤝‍🧑 紹介ごとに設定: {perRefer}%",
    btnSetMinWithdraw: "💸 最低出金額を設定: {minimumWithdraw} {currency}",
    btnSetMaxWithdraw: "💸 最高出金額を設定: {maximumWithdraw} {currency}",
    btnSetMaintenance: "🛠️ メンテナンス状態を設定: {maintenanceStatus}",
    btnSetWithdrawal: "🏧 出金状態を設定: {withdrawalStatus}",
    btnSetAutoWithdrawal: "🏧 自動出金状態を設定: {autowithStatus}",
    btnSetAlertsChannel: "🔴 アラートチャンネルを設定: {alertsChannel}",
    btnSetMerchantAPI: "🗝️ マーチャントAPIキーを設定: {merchantAPI}",
    btnSetPayoutAPI: "🗝️ ペイアウトAPIキーを設定: {payoutAPI}",
    btnViewUserBalance: "👀 ユーザー残高を表示",
    notAdmin: "<i>⚠️ あなたは {botLink} の管理者ではありません。</i>"
  }
};

var admin = Bot.getProperty("admin");
var users = user.telegramid;
var botLink = "@" + bot.name;
var userLang = User.getProperty("Language");
if (!userLang) {
  userLang = "EN";
}
var lang = adminPanelLangData[userLang] || adminPanelLangData["EN"];

if (users === admin) {
  var adminName = user.first_name;
  
  // Fetch the last deposit notification from a global property
  var lastDeposit = Bot.getProperty("lastDeposit") || lang.noRecentDeposits;
  
  var text =
    lang.welcome.replace("{adminName}", adminName).replace("{botLink}", botLink) + "\n\n" +
    lang.latestDepositTitle + "\n" + lastDeposit + "\n\n";
  
  // --- REAL STATISTICS (using your stored resources) ---
  var statusRes = Libs.ResourcesLib.anotherChatRes("status", "global");
  var totalWithdrawnRes = Libs.ResourcesLib.anotherChatRes("totalWithdrawn", "global");
  var totalDepositsRes = Libs.ResourcesLib.anotherChatRes("totalDeposits", "global");
  
  var currency = "USDT"; // Updated to USDT
  text += lang.realStatisticsTitle + "\n" +
          lang.totalMembers.replace("{status}", statusRes.value()) + "\n" +
          lang.totalWithdrawn.replace("{totalWithdrawn}", totalWithdrawnRes.value()).replace("{currency}", currency) + "\n" +
          lang.totalDeposited.replace("{totalDeposits}", totalDepositsRes.value()).replace("{currency}", currency) + "\n\n";
  
  // --- ADMIN SETTINGS ---
  var bonus = Bot.getProperty("bonus");
  var perRefer = Bot.getProperty("perRefer");
  var minimumWithdraw = Bot.getProperty("minimumWithdraw");
  var maximumWithdraw = Bot.getProperty("maximumWithdraw");
  var maintenanceStatus = Bot.getProperty("maintenanceStatus");
  var withdrawalStatus = Bot.getProperty("withdrawalStatus");
  var autowithStatus = Bot.getProperty("autowithStatus");
  var alertsChannel = Bot.getProperty("alertsChannel");
  var merchantAPI = Bot.getProperty("merchantAPI");
  var payoutAPI = Bot.getProperty("payoutAPI");
  
  text += lang.adminSettingsTitle + "\n" +
          lang.setCurrency.replace("{currency}", currency) + "\n" +
          lang.setBonus.replace("{bonus}", bonus).replace("{currency}", currency) + "\n" +
          lang.setPerRefer.replace("{perRefer}", perRefer) + "\n" +
          lang.setMinWithdraw.replace("{minimumWithdraw}", minimumWithdraw).replace("{currency}", currency) + "\n" +
          lang.setMaxWithdraw.replace("{maximumWithdraw}", maximumWithdraw).replace("{currency}", currency) + "\n" +
          lang.setMaintenance.replace("{maintenanceStatus}", maintenanceStatus) + "\n" +
          lang.setWithdrawal.replace("{withdrawalStatus}", withdrawalStatus) + "\n" +
          lang.setAutoWithdrawal.replace("{autowithStatus}", autowithStatus) + "\n" +
          lang.setAlertsChannel.replace("{alertsChannel}", alertsChannel) + "\n" +
          lang.setMerchantAPI.replace("{merchantAPI}", merchantAPI) + "\n" +
          lang.setPayoutAPI.replace("{payoutAPI}", payoutAPI);
  
  var buttons = [
    [
      { text: lang.btnAddBalance, callback_data: "/addBalance" },
      { text: lang.btnRemoveBalance, callback_data: "/removeBalance" }
    ],
    [
      { text: lang.btnBanUser, callback_data: "/banUser" },
      { text: lang.btnUnbanUser, callback_data: "/unbanUser" }
    ],
    [
      { text: lang.btnSetChannels, callback_data: "/setChannels" },
      { text: lang.btnBroadcast, callback_data: "/broadcast" }
    ],
    [
      { text: lang.btnSetCurrency.replace("{currency}", currency), callback_data: "/setCurrency" }
    ],
    [
      { text: lang.btnSetBonus.replace("{bonus}", bonus).replace("{currency}", currency), callback_data: "/setBonus" }
    ],
    [
      { text: lang.btnSetPerRefer.replace("{perRefer}", perRefer), callback_data: "/setPerRefer" }
    ],
    [
      { text: lang.btnSetMinWithdraw.replace("{minimumWithdraw}", minimumWithdraw).replace("{currency}", currency), callback_data: "/setMinimumWithdraw" }
    ],
    [
      { text: lang.btnSetMaxWithdraw.replace("{maximumWithdraw}", maximumWithdraw).replace("{currency}", currency), callback_data: "/setMaximumWithdraw" }
    ],
    [
      { text: lang.btnSetMaintenance.replace("{maintenanceStatus}", maintenanceStatus), callback_data: "/setMaintenanceStatus" }
    ],
    [
      { text: lang.btnSetWithdrawal.replace("{withdrawalStatus}", withdrawalStatus), callback_data: "/setWithdrawalStatus" }
    ],
    [
      { text: lang.btnSetAutoWithdrawal.replace("{autowithStatus}", autowithStatus), callback_data: "/setAutoWithdrawalStatus" }
    ],
    [
      { text: lang.btnSetAlertsChannel.replace("{alertsChannel}", alertsChannel), callback_data: "/setAlertsChannel" }
    ],
    [
      { text: lang.btnSetMerchantAPI.replace("{merchantAPI}", merchantAPI), callback_data: "/setMerchantAPIKey" }
    ],
    [
      { text: lang.btnSetPayoutAPI.replace("{payoutAPI}", payoutAPI), callback_data: "/setPayoutAPIKey" }
    ],
    [
      { text: lang.btnViewUserBalance, callback_data: "/viewuserbalance" }
    ]
  ];
  
  Api.sendMessage({
    text: text,
    reply_markup: { inline_keyboard: buttons },
    parse_mode: "html"
  });
} else {
  var notAdminText = lang.notAdmin.replace("{botLink}", botLink);
  Api.sendMessage({ text: notAdminText, parse_mode: "html" });
}
